### ISSUE TITLE
Testnet v0.5.0-alpha checklist

### ISSUE THREAD

**Issue by faddat** [galaxypi/galaxy#50]
**Description**
Testnet v0.5.0-alpha

**Items**
- [ ] 10 minute block times to improve sync speed when demoing galaxy #22 (ish)
- [ ] Increase the number of validators #22 
- [ ] In Testnet v0.5.0-alpha or Testnet v0.6.0-alpha, adapt https://explorecosmos.network/ to our needs
- [x] #18 - Make the bash script better
- [x] #67 - Apply new macOS install script changes to Linux install script
- [ ] #27 - Implement semantic versioning
- [ ] Create documentation for people who want to operate validators
- [ ] [Change forth tag name to v0.4.0-alpha](https://github.com/galaxypi/galaxy/issues/57)
- [ ] Create release `v0.5.0-alpha`

**Comment by guylepage3** [comment]
Sorry @faddat I got the semantic versioning guidelines wrong for our product. We should be on `Testnet v0.5.0-alpha` moving toward `Testnet v0.6.0-alpha`.

- See https://semver.org/

**Comment by guylepage3** [comment]
Also.. can you add #18 to the list of requirements above? And let's make them checkboxes so that we can check them off as they are complete.  Thank you.
