### ISSUE TITLE
Setup CircleCI build tests and alerts for Galaxy

### ISSUE THREAD

**Issue by guylepage3** [galaxypi/galaxy#62]
**Description**
Setup CircleCI build tests for Galaxy. So that we stay on top of passing or failing builds.

**Tasks**
- [ ] Add SSH to Galaxy GitHub
- [ ] Setup basic "Hello World" build test
- [ ] Add team members

**Comment by guylepage3** [comment]
@faddat can you create a CircleCI account so that I may add you? Thank you sir.
