### ISSUE TITLE
Update GitHub jargon

### ISSUE THREAD

**Issue by guylepage3** [galaxypi/galaxy#77]
**Description**
Update GitHub jargon. See https://github.com/galaxypi/galaxy.ooo/issues/32 and https://github.com/galaxypi/galaxy/pull/75

**Tasks**
Where necessary....
- [x] Need to update all README.md files to include "Galaxy is a blockchain agnostic node network and protocol offering services to decentralized platforms" in the header.
- [x] Replace part of each Roadmap section content with...
```
Galaxy's mission is to become the world's largest blockchain agnostic, always on, node network and protocol offering services to decentralized platforms.

We are looking to accomplish this by executing the following;

- [ ] Building and maintaining the Galaxy blockchain and protocol.
- [ ] Designing and building beautiful modified tiny computers (Raspberry Pi) 
      as Galaxy nodes.
- [ ] Providing an exceptional API, SDK and marketplace experience that allows
      developers to easily access and build on top of the Galaxy node network. 
- [ ] A simple and easy node owner interface and incentive program to 
      incentivize node owners.
- [ ] Provide the best experience for developers to quickly deploy node 
      modules, apps and services to decentralized platforms.
```

**Comment by guylepage3** [comment]
Done
